# Site settings
title: Proneet Sharma
email: proneetsharma@outlook.com
# url: https://github.com/jeromelachaud/freelancer-theme
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Graduate Research Assistant at German Research Centre for Artificial Intelligence (DFKI)"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary: 18bc9c #80B3FF
  # primary-rgb: "24,288,156" #"128,179,255"
  # secondary: 2c3e50 #FD6E8A
  # secondary-dark: 233140 #A2122F

  primary: 2F3437
  other-primary: 101010
  # primary-rgb: "128,179,255"
  primary-rgb: "196,198,203"
  secondary: D0A937
  secondary-dark: 59563B


# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ProneetSharma
  - title: linkedin
    url: https://www.linkedin.com/in/proneet-sharma
  - title: github
    url: https://github.com/proneetsharma
  - title: instagram
    url: https://www.instagram.com/proneet.sharma

# Postal address (add as many lines as necessary)
address:
  - line: Bonn, Germany

# Credits content
credits: 'proneetsharma@outlook.com'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
